### ISSUE TITLE
RustDesk

### ISSUE THREAD

**Issue by raman9000** [truecharts/.github#14]
### Short description of the app

RustDesk is a remote access and remote control software, allowing maintenance of computers and other devices. The RustDesk client is available for different operating systems. RustDesk has the aspiration to be an open source alternative for Remote desktop software like TeamViewer or AnyDesk

### Sources

https://rustdesk.com/docs/en/self-host/install/

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by Ornias1993** [comment]
Wrong repo, this is just a technical repo. Like all `.github` repo's
