### ISSUE TITLE
[Feat] Add TCP and UDP support to Traefik

### ISSUE THREAD

**Issue by archiso7** [truecharts/.github#8]
### Is your feature request related to a problem?

There is a lot of services that can be run on Truenas that use TCP or UDP such as OpenVPN or a minecraft server. It is frustrating that inorder to use these services another port has to be forwarded because they cannot run through Traefik's reverse proxy.

### Describe the solution you'd like

I would like TCP and UDP support to be added to Traefik. The main version of Traefik directly from Traefik Labs has support for TCP and UDP, so why shouldn't the Truecharts one have support for them?

### Describe alternatives you've considered

An alternative to this is adding another reverse proxy program that supports TCP and UDP to Truecharts.

### I've read and agree with the following

- [X] I've checked all open and closed issues and my request is not there.
- [X] I've checked all open and closed pull requests and my request is not there.

**Comment by woodsb02** [comment]
I think this issue was opened against the wrong repository (I did the same thing). I’ve opened a similar issue (mine only asks for TCP, but I’ll add a comment linking this this issue).

https://github.com/truecharts/charts/issues/3865

Suggest closing this issue?

**Comment by Ornias1993** [comment]
Yes it is.
Thanks for noticing!
